<?php

include_once('OAuth.php');

class Pesaapal
{

    public $token =  NULL;
    public $params  =  NULL;


    public   $consumer_key = 'HJSRUdBWo+Z8tf/Fy267KubPYne1bUyf';

    public  $consumer_secret = 'WnZOipCS5S5cEEnh5VttT6gBFXk=';

    public $signature_method;

    /**
     * Pesaapal constructor.
     * @param null $token
     * @param null $params
     * @param string $consumer_key
     * @param string $consumer_secret
     * @param OAuthSignatureMethod_HMAC_SHA1 $signature_method
     */
    public function __construct($token, $params, $consumer_key, $consumer_secret)
    {
        $this->token = $token;
        $this->params = $params;
        $this->consumer_key = $consumer_key;
        $this->consumer_secret = $consumer_secret;
        $this->signature_method  = new OAuthSignatureMethod_HMAC_SHA1();
    }

    public function get_iframe()
    {
        $iframelink = 'https://demo.pesapal.com/api/PostPesapalDirectOrderV4';//change to


        $amount = $_POST['amount'];
        $amount = number_format($amount, 2);//format amount to 2 decimal places

        $desc = $_POST['description'];
        $type = $_POST['type']; //default value = MERCHANT
        $reference = $_POST['reference'];//unique order id of the transaction, generated by merchant
        $first_name = $_POST['first_name'];
        $last_name = $_POST['last_name'];
        $email = $_POST['email'];
        $phonenumber = '';

        $callback_url = 'http://www.yourdomain.com/redirect.php';

        $post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"https://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"https://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"https://www.pesapal.com\" />";
        $post_xml = htmlentities($post_xml);

        $consumer = new OAuthConsumer($this->consumer_key, $this->consumer_secret);

        $iframe_src = OAuthRequest::from_consumer_and_token($consumer, $this->token, "GET", $iframelink, $this->params);
        $iframe_src->set_parameter("oauth_callback", $callback_url);
        $iframe_src->set_parameter("pesapal_request_data", $post_xml);
        $iframe_src->sign_request($this->signature_method, $consumer, $this->token);



    }




}